src/main/java/org/springframework/samples/petclinic/model/Vet.java
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;

import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;

/**
 * Simple JavaBean domain object representing a veterinarian.
 *
 * @author Ken Krebs
 * @author Juergen Hoeller
 * @author Sam Brannen
 * @author Arjen Poutsma
 */
@Entity
@Table(name = "vets")
public class Vet extends Person {

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "vet_specialties", joinColumns = @JoinColumn(name = "vet_id"),
            inverseJoinColumns = @JoinColumn(name = "specialty_id"))
    private Set<Specialty> specialties;


    protected void setSpecialtiesInternal(Set<Specialty> specialties) {
        this.specialties = specialties;
    }
    
    public void newSetSpecialties() {
    	this.specialties = new HashSet<Specialty>();
    }

    protected Set<Specialty> getSpecialtiesInternal() {
        if (this.specialties == null) {
            this.specialties = new HashSet<Specialty>();
        }
        return this.specialties;
    }

    @XmlElement
    public List<Specialty> getSpecialties() {
        List<Specialty> sortedSpecs = new ArrayList<Specialty>(getSpecialtiesInternal());
        PropertyComparator.sort(sortedSpecs, new MutableSortDefinition("name", true, true));
        return Collections.unmodifiableList(sortedSpecs);
    }

    public int getNrOfSpecialties() {
        return getSpecialtiesInternal().size();
    }

    public void addSpecialty(Specialty specialty) {
        getSpecialtiesInternal().add(specialty);
    }
    
    
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "vet", fetch = FetchType.EAGER)
    private Set<Visit> visits;
    
    protected void setVisitsInternal(Set<Visit> visits) {
        this.visits = visits;
    }

    protected Set<Visit> getVisitsInternal() {
        if (this.visits == null) {
            this.visits = new HashSet<Visit>();
        }
        return this.visits;
    }

    public List<Visit> getVisits() {
        List<Visit> sortedVisits = new ArrayList<Visit>(getVisitsInternal());
        PropertyComparator.sort(sortedVisits, new MutableSortDefinition("date", false, false));
        return Collections.unmodifiableList(sortedVisits);
    }

    public void addVisit(Visit visit) {
        getVisitsInternal().add(visit);
        visit.setVet(this);
    }
    
    @Column(name = "house_calls")
    protected Boolean houseCalls;


	public Boolean getHouseCalls() {
		return houseCalls;
	}

	public void setHouseCalls(Boolean houseCalls) {
		this.houseCalls = houseCalls;
	}
	
	@Column(name = "telephone")
    protected String telephone;


	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	
	
	
 
}

src/main/java/org/springframework/samples/petclinic/model/Vets.java
/*
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Simple domain object representing a list of veterinarians. Mostly here to be used for the 'vets' {@link
 * org.springframework.web.servlet.view.xml.MarshallingView}.
 *
 * @author Arjen Poutsma
 */
@XmlRootElement
public class Vets {

    private List<Vet> vets;

    @XmlElement
    public List<Vet> getVetList() {
        if (vets == null) {
            vets = new ArrayList<Vet>();
        }
        return vets;
    }

}

src/main/java/org/springframework/samples/petclinic/web/VetController.java
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.web;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.samples.petclinic.model.Specialty;
import org.springframework.samples.petclinic.model.Vet;
import org.springframework.samples.petclinic.model.Vets;
import org.springframework.samples.petclinic.service.ClinicService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;

/**
 * @author Juergen Hoeller
 * @author Mark Fisher
 * @author Ken Krebs
 * @author Arjen Poutsma
 */
@Controller
public class VetController {

    private final ClinicService clinicService;

    @ModelAttribute("specialties")
    public Collection<Specialty> populateSpecialties() {
        return this.clinicService.findSpecialties();
    }

    @Autowired
    public VetController(ClinicService clinicService) {
        this.clinicService = clinicService;
    }

    @RequestMapping("/vets")
    public String showVetList(Map<String, Object> model) {
        // Here we are returning an object of type 'Vets' rather than a collection of Vet objects 
        // so it is simpler for Object-Xml mapping
        Vets vets = new Vets();
        vets.getVetList().addAll(this.clinicService.findVets());
        model.put("vets", vets);
        return "vets/vetList";
    }
    
   
    @RequestMapping(value = "/vets/new", method = RequestMethod.GET)
    public String initCreationForm(Map<String, Object> model) {
        Vet vet = new Vet();
        model.put("vet", vet);
        return "vets/createOrUpdateVetForm";
    }
    
    @RequestMapping(value = "/vets/new", method = RequestMethod.POST)
    public String processCreationForm(@ModelAttribute("vet") Vet vet,@RequestParam("specialties") String specialty, BindingResult result, SessionStatus status) {
    	new VetValidator().validate(vet, result);
        if (result.hasErrors()) {
            return "vets/createOrUpdateVetForm";
        } else {
        	
        	if (specialty!=null && specialty.length()>0) {
	        	vet.newSetSpecialties();
	        	List<String> items = Arrays.asList(specialty.split("\\s*,\\s*"));
	        	for (String string : items) {
	        		vet.addSpecialty(this.clinicService.findSpecialtyByName(string));
				}
        	}
        	
            this.clinicService.saveVet(vet);
            status.setComplete();
            return "redirect:/vets/" + vet.getId();
        }
    }

    @RequestMapping(value = "/vets/{vetId}/edit", method = RequestMethod.GET)
    public String initUpdateVetForm(@PathVariable("vetId") int vetId, Model model) {
        Vet vet = this.clinicService.findVetById(vetId);
        model.addAttribute(vet);
        return "vets/createOrUpdateVetForm";
    }

    @RequestMapping(value = "/vets/{vetId}/edit", method = RequestMethod.PUT)
    public String processUpdateVetForm(@PathVariable("vetId") int vetId, @Valid Vet vet, @RequestParam("specialties") String specialty, BindingResult result, SessionStatus status) {
    	new VetValidator().validate(vet, result);
        if (result.hasErrors()) {
            return "vets/createOrUpdateVetForm";
        } else {
        	Vet vetToSave = this.clinicService.findVetById(vetId);
        	vetToSave.setFirstName(vet.getFirstName());
        	vetToSave.setLastName(vet.getLastName());
        	vetToSave.setHouseCalls(vet.getHouseCalls());
        	vetToSave.setTelephone(vet.getTelephone());
        	
        	if (specialty!=null && specialty.length()>0) {
	        	vetToSave.newSetSpecialties();
	        	List<String> items = Arrays.asList(specialty.split("\\s*,\\s*"));
	        	for (String string : items) {
	        		vetToSave.addSpecialty(this.clinicService.findSpecialtyByName(string));
				}
        	}
        	
    
            this.clinicService.saveVet(vetToSave);
            status.setComplete();
            return "redirect:/vets/{vetId}";
        }
    }


    @RequestMapping("/vets/{vetId}")
    public ModelAndView showVet(@PathVariable("vetId") int vetId) {
        ModelAndView mav = new ModelAndView("vets/vetDetails");
        mav.addObject(this.clinicService.findVetById(vetId));
        return mav;
    }
    
    @RequestMapping("/vets/{vetId}/today")
    public ModelAndView showVetToday(@PathVariable("vetId") int vetId) {
        ModelAndView mav = new ModelAndView("vets/vetDetails");
        mav.addObject(this.clinicService.findVetById(vetId));
        mav.addObject("todayVisits",this.clinicService.findTodayVisits(vetId));
        return mav;
    }

}

src/main/webapp/WEB-INF/jsp/vets/createOrUpdateVetForm.jsp
<!DOCTYPE html> 

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="petclinic" tagdir="/WEB-INF/tags" %>


<html lang="en">

<jsp:include page="../fragments/headTag.jsp"/>

<body>
<div class="container">
    <jsp:include page="../fragments/bodyHeader.jsp"/>
    <c:choose>
        <c:when test="${vet['new']}"><c:set var="method" value="post"/></c:when>
        <c:otherwise><c:set var="method" value="put"/></c:otherwise>
    </c:choose>

    <h2>
        <c:if test="${vet['new']}">New </c:if> Vet
    </h2>
    <form:form modelAttribute="vet" method="${method}" class="form-horizontal" id="edit-vet-form">
    
        <style type="text/css">
			input {
   				width: 100px;
			}
			select{
				width: 100px;
			}
		</style>
		<div style="width:100%; overflow: hidden;">
		    <div style="float:left; width:50%;">
		        <petclinic:inputField label="First Name" name="firstName"/>
        		<petclinic:inputField label="Last Name" name="lastName"/>
		    </div>
		    <div style="float:right; width:50%;">
		        <petclinic:selectField name="specialties" label="Specialty" names="${specialties}" size="3"/>
		    	<petclinic:checkboxField label="House Calls" name="houseCalls"></petclinic:checkboxField>
		    	<petclinic:inputField label="Telephone" name="telephone"/>
		    </div>
		</div>
       
        <div class="form-actions">
            <c:choose>
                <c:when test="${vet['new']}">
                    <button type="submit">Add Vet</button>
                </c:when>
                <c:otherwise>
                    <button type="submit">Update Vet</button>
                </c:otherwise>
            </c:choose>
        </div>
    </form:form>
    
    <jsp:include page="../fragments/footer.jsp"/>
    
</div>
</body>

</html>

src/main/webapp/WEB-INF/jsp/vets/vetDetails.jsp
<!DOCTYPE html> 

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="joda" uri="http://www.joda.org/joda/time/tags" %>
<%@ taglib prefix="petclinic" tagdir="/WEB-INF/tags" %>

<html lang="en">

<jsp:include page="../fragments/headTag.jsp"/>

<body>
<div class="container">
    <jsp:include page="../fragments/bodyHeader.jsp"/>

    <h2>Vet Information</h2>

    <table class="table table-striped" style="width:600px;">
        <tr>
            <th>First Name</th>
            <td><b><c:out value="${vet.firstName}"/></b></td>
        </tr>
        <tr>
            <th>Last Name</th>
            <td><b><c:out value="${vet.lastName}"/></b></td>
        </tr>
        <tr>
        	<th>Specialities</th>
				<td><c:forEach var="specialty" items="${vet.specialties}">
						<c:out value="${specialty.name}" />
					</c:forEach> 
					<c:if test="${vet.nrOfSpecialties == 0}">none</c:if></td>
		</tr>
		<tr>
            <th>House Calls</th>
            	<td><b><c:if test="${!vet.houseCalls}">No</c:if>
            	<c:if test="${vet.houseCalls}">Yes</c:if></b></td>
        </tr>
        <tr>
            <th>Telephone</th>
            <td><c:out value="${vet.telephone}"/></td>
        </tr>
        <tr>
            <td>
            	<c:choose>
	   				<c:when test="${todayVisits != null}">
	                </c:when>
		   			<c:otherwise> 
		   				<spring:url value="{vetId}/edit.html" var="editUrl">
		                    <spring:param name="vetId" value="${vet.id}"/>
		                </spring:url>
		                <a href="${fn:escapeXml(editUrl)}" class="btn btn-info">Edit Vet</a>
		   			</c:otherwise>
   				 </c:choose>
             </td>
         </tr>
    </table>
    
    <h2>Visits</h2>
	
	<c:choose>
	   <c:when test="${todayVisits != null}">
	   	<table class="table-condensed">
			<thead>
				<tr>
					<th>Visit Date</th>
					<th>Description</th>
					<th>Pet</th>
				</tr>
			</thead>
			<c:forEach var="visit" items="${todayVisits}">
				<tr>
					<td><joda:format value="${visit.date}" pattern="yyyy-MM-dd" /></td>
					<td><c:out value="${visit.description}" /></td>
					<td><c:out value="${visit.pet.name}" /></td>
				</tr>
			</c:forEach>
		</table>
	   </c:when>
	   <c:otherwise>
		<spring:url value="{vetId}/today" var="todayVisits">
			<spring:param name="vetId" value="${vet.id}"/>
		</spring:url>
		<a href="${fn:escapeXml(todayVisits)}">Only today visits</a>
		
		<table class="table-condensed">
			<thead>
				<tr>
					<th>Visit Date</th>
					<th>Description</th>
					<th>Pet</th>
					<th>Edit</th>
				</tr>
			</thead>
			<c:forEach var="visit" items="${vet.visits}">
				<tr>
					<td><joda:format value="${visit.date}" pattern="yyyy-MM-dd" /></td>
					<td><c:out value="${visit.description}" /></td>
					<td><c:out value="${visit.pet.name}" /></td>
					<td>
                       <spring:url value="/vets/{vetId}/pets/{petId}/visit/{visitId}/edit" var="visitUrl">
                       	  <spring:param name="vetId" value="${vet.id}"/>
                       	  <spring:param name="petId" value="${visit.pet.id}"/>
		                  <spring:param name="visitId" value="${visit.id}"/>
		              </spring:url>
		              <a href="${fn:escapeXml(visitUrl)}">Edit</a>
                   </td>
				</tr>
			</c:forEach>
		</table>
       </c:otherwise>
    </c:choose>
		
	

    <jsp:include page="../fragments/footer.jsp"/>

</div>

</body>

</html>

src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
<!DOCTYPE html> 

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="datatables" uri="http://github.com/dandelion/datatables" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<html lang="en">


<jsp:include page="../fragments/headTag.jsp"/>

<body>
<div class="container">
    <jsp:include page="../fragments/bodyHeader.jsp"/>

    <h2>Veterinarians</h2>

    <datatables:table id="vets" data="${vets.vetList}" cdn="true" row="vet" theme="bootstrap2" cssClass="table table-striped" paginate="false" info="false">
		<datatables:column title="Name" cssStyle="width: 150px;" display="html">
            <spring:url value="/vets/{vetId}.html" var="vetUrl">
                <spring:param name="vetId" value="${vet.id}"/>
            </spring:url>
            <a href="${fn:escapeXml(vetUrl)}"><c:out value="${vet.firstName} ${vet.lastName}"/></a>
        </datatables:column>
        <datatables:column title="Specialties">
            <c:forEach var="specialty" items="${vet.specialties}">
                <c:out value="${specialty.name}"/>
            </c:forEach>
            <c:if test="${vet.nrOfSpecialties == 0}">none</c:if>
        </datatables:column>
        <datatables:column title="House Calls">
            <c:if test="${!vet.houseCalls}">No</c:if>
            <c:if test="${vet.houseCalls}">Yes</c:if>
        </datatables:column>
    </datatables:table>
    
    <table class="table-buttons">
        <tr>
            <td>
            	<spring:url value="vets/new.html" var="addUrl"/>
                <a href="${fn:escapeXml(addUrl)}"  class="btn btn-success">Add New Vet</a></td>
            <td>
                <a href="<spring:url value="/vets.xml" htmlEscape="true" />">View as XML</a>
            </td>
            <td>
                <a href="<spring:url value="/vets.atom" htmlEscape="true" />">Subscribe to Atom feed</a>
            </td>
        </tr>
    </table>

    <jsp:include page="../fragments/footer.jsp"/>
</div>
</body>

</html>